### PR TITLE
Add benchmark for fulfillment warehouse

### PR DESCRIPTION
**Pull request by 8r2y5**
I want to merge this change because I want to add benchmark for fulfillment warehouse resolvers

# Impact

* [ ] New migrations
* [ ] New/Updated API fields or mutations
* [ ] Deprecated API fields or mutations
* [ ] Removed API types, fields, or mutations
* [ ] Documentation needs to be updated

# Pull Request Checklist

* [ ] Privileged queries and mutations are guarded by proper permission checks
* [ ] Database queries are optimized and the number of queries is constant
* [ ] Database migration files are up to date
* [ ] The changes are tested
* [ ] GraphQL schema and type definitions are up to date
* [ ] Changes are mentioned in the changelog

### CODE REVIEW

**Comment by patrys** [comment]
Task linked: [SALEOR-3729 Optimize Fulfillment type resolvers](https://app.clickup.com/t/2549495/SALEOR-3729)

**Review by maarcingebala — APPROVED** [review]

**Review by IKarbowiak — CHANGES_REQUESTED** [review]
We should also extend the fixture `test_fulfillment_query` as there is only one `Warehouse` so we do not test the performance of fetching warehouses.

**Comment by tomaszszymanski129** [comment]
@IKarbowiak we actually do, the resolver fires for each order so in this case query count will drop anyway as the old resolver added up to 3 extra queries for each. But I agree, more objects is better when it comes to benchmarks, we should add some.

**Comment by IKarbowiak** [comment]
@tomaszszymanski129 I checked locally the test that uses this query and there was only one warehouse instance.

**Review by IKarbowiak — APPROVED** [review]

**Review by maarcingebala — APPROVED** [review]

**Pull request merged**
