### PR TITLE
Subscription Feature

### PR DESCRIPTION
**Pull request by farookibrahim**
I want to merge this change because it adds subscription feature. Subscription will create when user paid for an order with any one of line item has subscription product variant. Please note I tested this feature with stripe gateway only.

#2466

# Impact

* [x] New migrations
* [x] New/Updated API fields or mutations
* [ ] Deprecated API fields or mutations
* [ ] Removed API types, fields, or mutations
* [x] Documentation needs to be updated

# Pull Request Checklist

* [x] Privileged queries and mutations are guarded by proper permission checks
* [x] Database queries are optimized and the number of queries is constant
* [x] Database migration files are up to date
* [x] The changes are tested
* [ ] GraphQL schema and type definitions are up to date
* [ ] Changes are mentioned in the changelog

### CODE REVIEW

**Comment by patrys** [comment]
Hello and thanks for the contribution. As the core team is currently very busy with work related with the 3.0 release and Saleor Cloud, it can take some time before we'll be able to review all pull requests submitted by the community. Thank you for your patience!

**Comment by Roni1993** [comment]
@patrys is there any ETA on when this PR will be merged/reviewed?
i wanted to use saleor for Subscripts only & PR seems like it would support it

**Comment by janbaykara** [comment]
Hi @patrys, congrats on the Saleor v3 release! Can we get an update on when this PR (or the more general feature request of subscription billing #2466) will be addressed by the core team?

**Comment by maarcingebala** [comment]
We discussed the status of this PR recently and have decided that it's too broad scope currently and we won't merge it to the core. We're trying to limit the features added to core to the minimum and focus on extensibility via webhooks and building new features as Saleor Apps. We really appreciate the amount of work put into this PR and willing to contribute to the platform 🙌 .

**Pull request closed without merging**
