### PR TITLE
Add metadata on order line payload notifications

### PR DESCRIPTION
**Pull request by CarlesLopezMagem**
I want to merge this change because I want to add OrderLine metadata on order notifications payloads

# Impact

* [ ] New migrations
* [ ] New/Updated API fields or mutations
* [ ] Deprecated API fields or mutations
* [ ] Removed API types, fields, or mutations
* [ ] Documentation needs to be updated

# Pull Request Checklist

* [ ] Privileged queries and mutations are guarded by proper permission checks
* [ ] Database queries are optimized and the number of queries is constant
* [ ] Database migration files are up to date
* [x] The changes are tested
* [x] GraphQL schema and type definitions are up to date
* [ ] Changes are mentioned in the changelog

### CODE REVIEW

**Review by IKarbowiak — COMMENTED** [review]
Looks good 🎉 . I'm only wondering if the private metadata shouldn't be added too. @fowczarek what do you think?

Please also add a changelog entry.

**Comment by fowczarek** [comment]
I don't think that we should send private metadata to external apps e.g we don't send any private metadata to tax apps.

**Comment by IKarbowiak** [comment]
@fowczarek But we include the `private_metadata` for order payload: https://github.com/saleor/saleor/blob/main/saleor/order/notifications.py#L208. Because of that, I'm wondering if we shouldn't include it in order lines too.

**Comment by IKarbowiak** [comment]
We agreed that `private_metadata` shouldn't be included. @CarlesLopezMagem could you only add a changelog entry?

**Comment by CarlesLopezMagem** [comment]
@IKarbowiak @fowczarek Yeah, I'm agreed too (see https://github.com/saleor/saleor/blob/main/saleor/order/notifications.py#L270). And I changed changelog too! ;)

**Review by IKarbowiak — APPROVED** [review]

**Review by fowczarek — APPROVED** [review]

**Comment by fowczarek** [comment]
Thanks for contributing to Saleor @CarlesLopezMagem  🎉

**Pull request merged**
