### PR TITLE
SALEOR-4420 missing quantization in webhooks

### PR DESCRIPTION
**Pull request by kuchichan**
I want to merge this change because...

# Impact

* [ ] New migrations
* [ ] New/Updated API fields or mutations
* [ ] Deprecated API fields or mutations
* [ ] Removed API types, fields, or mutations
* [ ] Documentation needs to be updated

# Pull Request Checklist

* [ ] Privileged queries and mutations are guarded by proper permission checks
* [ ] Database queries are optimized and the number of queries is constant
* [ ] Database migration files are up to date
* [ ] The changes are tested
* [ ] GraphQL schema and type definitions are up to date
* [ ] Changes are mentioned in the changelog

### CODE REVIEW

**Review by IKarbowiak — APPROVED** [review]

**Comment by korycins** [comment]
@maarcingebala  @kuchichan This is something which would be good to have in 3.0 also. Without this, it is really hard to build nice emails

**Comment by maarcingebala** [comment]
@korycins Yes, once this is tested and merged we can move it to 3.0.

**Review by tomaszszymanski129 — APPROVED** [review]

**Comment by maarcingebala** [comment]
Tested and it works fine, @kuchichan would you have time to port these changes to 3.0?

**Comment by kuchichan** [comment]
I wish I had, really - I'll ask my PM tomorrow.

**Pull request merged**
