### PR TITLE
Change `discount_promotionrule_variants` `id` to `bigint`

### PR DESCRIPTION
**Pull request by IKarbowiak**
Change `discount_promotionrule_variants` `id` to `bigint`

Resolves comment: https://github.com/saleor/saleor/issues/15145#issuecomment-1874093887

# Impact

- [ ] New migrations
- [ ] New/Updated API fields or mutations
- [ ] Deprecated API fields or mutations
- [ ] Removed API types, fields, or mutations

# Docs

- [ ] Link to documentation:

# Pull Request Checklist

- [ ] Privileged queries and mutations are either absent or guarded by proper permission checks
- [ ] Database queries are optimized and the number of queries is constant
- [ ] Database migrations are either absent or optimized for zero downtime
- [ ] The changes are covered by test cases
- [ ] All new fields/inputs/mutations have proper labels added (`ADDED_IN_X`, `PREVIEW_FEATURE`, etc.)
- [ ] All migrations have proper dependencies
- [ ] All indexes are added concurrently in migrations
- [ ] All RunSql and RunPython migrations have revert option defined

### CODE REVIEW

**Review by NyanKiyoshi — CHANGES_REQUESTED** [review]
Why not use Django's `BigAutoField` instead of using raw SQL? https://docs.djangoproject.com/en/3.2/ref/models/fields/#bigautofield

**Comment by IKarbowiak** [comment]
@NyanKiyoshi It's an ID on the cross-reference table so I don't want to define this table in the code only to change id to `BigAutoField`. 
Also, I checked what the SQL statements are under the django migration for changing the `id` to `BigAutoField` and it contains the same logic that is added in this migration.

**Review by korycins — APPROVED** [review]

**Comment by NyanKiyoshi** [comment]
> @NyanKiyoshi It's an ID on the cross-reference table so I don't want to define this table in the code only to change id to `BigAutoField`. Also, I checked what the SQL statements are under the django migration for changing the `id` to `BigAutoField` and it contains the same logic that is added in this migration.

This sounds dangerous to me because Django may run checks (e.g., new relations added) and think it's int32 while the value is int64 which could lead to major bugs on some datasets. As well it hides the actual types from the developers, maintainers will also not check dozens of migration files and thus will be surprised if unexpected behaviors start happening due to using int64.

IMO the effort of defining the M2M table in Django ORM is worth it due to the risks the current migration brings.

**Comment by IKarbowiak** [comment]
@NyanKiyoshi, thank you for the explenation, so I will change that :)

**Review by zedzior — APPROVED** [review]

**Review by korycins — APPROVED** [review]

**Pull request merged**
