### PR TITLE
Add unit test exposing potential duplicate webhooks

### PR DESCRIPTION
**Pull request by stnatic**
While reviewing another pull request, I've noticed this anti pattern - filtering by a reverse foreign key without `distinct`
```
webhooks = webhooks.filter(
        is_active=True,
        app__is_active=True,
        events__event_type__in=[event_type, WebhookEventAsyncType.ANY],
        **permissions,
)
```

I'd recommend to either add distinct or to add a comment why is it not needed. It doesn't seem like the `createWebhook` mutation is protected against it.

The unit test shows en example scenario where `_get_webhooks_for_event` could return a single webhook twice, since it was configured to be triggered by both `event_type` and `ANY`.

```
>       assert len(webhooks) == 1
E       assert 2 == 1
E        +  where 2 = len(<QuerySet [<Webhook: Simple webhook>, <Webhook: Simple webhook>]>)
```

# Impact

* [ ] New migrations
* [ ] New/Updated API fields or mutations
* [ ] Deprecated API fields or mutations
* [ ] Removed API types, fields, or mutations
* [ ] Documentation needs to be updated

# Pull Request Checklist

* [ ] Privileged queries and mutations are guarded by proper permission checks
* [ ] Database queries are optimized and the number of queries is constant
* [ ] Database migration files are up to date
* [ ] The changes are tested
* [ ] GraphQL schema and type definitions are up to date
* [ ] Changes are mentioned in the changelog

### CODE REVIEW

**Comment by L3str4nge** [comment]
@stnatic Your test is failing. Could you take a look?

**Comment by stnatic** [comment]
@L3str4nge That's the point - it shows how a single webhook is returned twice by that helper function. The code can be easily adjusted by adding `distinct` but first I want to make sure that it wasn't omitted on purpose (performance reasons? although I think in this case it's negligible)

**Comment by L3str4nge** [comment]
Why we can't just fix that? :D

**Comment by maarcingebala** [comment]
I think it should be rewritten with subqueries - a separate query to get active apps, then another to get the right event types, and the third one combining it all together.

**Comment by stnatic** [comment]
I would suggest to consider this together with https://github.com/saleor/saleor/issues/9138 as this is also the piece of code that makes ANY_EVENT apply to sync webhooks

**Pull request closed without merging**
