### PR TITLE
Fixed variant list in cls.process_checkout_lines

### PR DESCRIPTION
**Pull request by sixthgear**
- Used the same method found in complete_checkout.py to itemize line quantities and variants.
- This will ensure both lists refer to the same line/variant when doing stock availability calculations
- This will also allow multiple lines to point to the same variant, since the lists will now be of the same length
- see check_stock_quantity_bulk in saleor/warehouse/availability.py for the place where this change will be apparent.
- ```for variant, quantity in zip(variants, quantities):```

I want to merge this change because...

- This fixes the error identified in issue #11056

# Impact

* [ ] New migrations
* [ ] New/Updated API fields or mutations
* [ ] Deprecated API fields or mutations
* [ ] Removed API types, fields, or mutations
* [ ] Documentation needs to be updated

# Pull Request Checklist

* [ ] Privileged queries and mutations are guarded by proper permission checks
* [ ] Database queries are optimized and the number of queries is constant
* [ ] Database migration files are up to date
* [ ] The changes are tested
* [ ] GraphQL schema and type definitions are up to date
* [ ] Changes are mentioned in the changelog

### CODE REVIEW

**Review by fowczarek — COMMENTED** [review]
LGTM 🎉 
@sixthgear could you also add a test case for the described situation?

**Comment by sixthgear** [comment]
> LGTM 🎉 @sixthgear could you also add a test case for the described situation?

@fowczarek I'd love to do that. I've been deep-diving the saleor architecture for a project.

Unfortunately, I'm currently in crunch mode to release our new storefront and I'm still getting acquainted with your testing setup and conventions. I was hoping my step-by-step in the original issue would help someone from the core team write a test case for now. 

Alternatively, if you're willing to wait a bit I'll loop back to this in a few days and try to provide a test.

**Comment by sixthgear** [comment]
@fowczarek I've added a test case for you. I've confirmed that it fails on tag 3.8 but passes on my PR.

**Comment by fowczarek** [comment]
> @fowczarek I've added a test case for you. I've confirmed that it fails on tag 3.8 but passes on my PR.

@sixthgear greater to here that you test it this way. I'm passing it to the team review and QA process after review.

**Comment by sixthgear** [comment]
Don't forget this one review team! In my opinion, this is actually a pretty significant bug for anyone using the track inventory feature.

**Review by IKarbowiak — APPROVED** [review]

**Review by fowczarek — APPROVED** [review]

**Comment by fowczarek** [comment]
Passed to QA.

**Review by eCzerniak — APPROVED** [review]

**Comment by fowczarek** [comment]
Thanks for contributing to Saleor @sixthgear 🎉

**Pull request merged**
