### PR TITLE
Pass correct list of order lines to order_added_products_event

### PR DESCRIPTION
**Pull request by L3str4nge**
Pass `List[Tuple[int, OrderLine]]` to order_added_products_event

# Impact

* [ ] New migrations
* [ ] New/Updated API fields or mutations
* [ ] Deprecated API fields or mutations
* [ ] Removed API types, fields, or mutations
* [ ] Documentation needs to be updated

# Pull Request Checklist

* [ ] Privileged queries and mutations are guarded by proper permission checks
* [ ] Database queries are optimized and the number of queries is constant
* [ ] Database migration files are up to date
* [ ] The changes are tested
* [ ] GraphQL schema and type definitions are up to date
* [ ] Changes are mentioned in the changelog

### CODE REVIEW

**Comment by patrys** [comment]
Task linked: [SALEOR-3130 CreateDraftOrder mutation generates invalid event](https://app.clickup.com/t/2549495/SALEOR-3130)

**Review by IKarbowiak — APPROVED** [review]

**Review by jakubkuc — APPROVED** [review]

**Review by fowczarek — APPROVED** [review]

**Comment by maarcingebala** [comment]
@L3str4nge Should I pass it to QA, I mean is there a meaningful way to test it?

**Comment by L3str4nge** [comment]
> @L3str4nge Should I pass it to QA, I mean is there a meaningful way to test it?

It is always good to check by QAs. We will ensure that event will be send properly.

**Comment by maarcingebala** [comment]
@L3str4nge Sounds good, can you provide some instructions on how they can test it? I'm afraid from the task description it might be difficult to understand as it's about some implementation details.

**Review by tomaszszymanski129 — APPROVED** [review]

**Comment by L3str4nge** [comment]
@maarcingebala Sorry fot the delay. I've added testing notes in the task description.

**Pull request merged**
