### PR TITLE
No need for .nvmrc, since we mention engine into packge.json

### PR DESCRIPTION
**Pull request by HazemKhaled**
We have different versions for node here, one into `.nvmrc` which version 10.x and another one into `package.json` version 14 to 15 ... I prefer to keep `package.json`

# Impact

* [ ] New migrations
* [ ] New/Updated API fields or mutations
* [ ] Deprecated API fields or mutations
* [ ] Removed API types, fields, or mutations
* [ ] Documentation needs to be updated

# Pull Request Checklist

* [ ] Privileged queries and mutations are guarded by proper permission checks
* [ ] Database queries are optimized and the number of queries is constant
* [ ] Database migration files are up to date
* [ ] The changes are tested
* [ ] GraphQL schema and type definitions are up to date
* [ ] Changes are mentioned in the changelog

### CODE REVIEW

**Comment by HazemKhaled** [comment]
Sure, what do you think about `lts/*` instead of specifying a specific version since we don't care much here about the version?

ref https://github.com/nvm-sh/nvm#nvmrc @maarcingebala

**Comment by maarcingebala** [comment]
Sounds good, but the current LTS is 16.13.2, so we should also update versions of `node` and `npm` defined in `package.json`.

**Comment by HazemKhaled** [comment]
You don't need both, `.nvmrc` file and `engine` in `package.json` ... just decide to use any of them instead of changing both every time

https://stackoverflow.com/questions/61403815/js-nvmrc-vs-package-json-engines

I've no problem to update both by the way

**Comment by maarcingebala** [comment]
OK, so let's stick with one version defined in `package.json`, anyone actually needing to use any of the npm commands with this repo should also understand how to set the correct version of Node.

**Comment by maarcingebala** [comment]
@HazemKhaled Could you rebase the PR against the `main` branch? We push all changes related to Saleor 3.1 to main, later during releases we move them to the `3.1` branch.

**Comment by crcastle** [comment]
I just stumbled over this a bit. It's unclear if this project requires [Node v10.15.2](https://github.com/saleor/saleor/blob/main/.nvmrc#L1) or [Node >=16 and <17](https://github.com/saleor/saleor/blob/main/package.json#L5).

**Pull request closed without merging**
