### PR TITLE
[RFC] Order attributes

### PR DESCRIPTION
**Pull request by IKarbowiak**
The goal is to allow users to use attributes in orders.

## General assumptions
- Order attributes will be defined in order settings.
- Only attributes defined in the order settings could be assigned to order.
- All orders will have the same set of attributes.
- When the new required attribute is assigned the order type, all existing orders will have this attribute value empty.
- The attributes could be assigned in the following mutations:
  - `OrderCreateFromCheckout`,
  - `OrderUpdate`,
  - `DraftOrderUpdate`,
  - `DraftOrderCreate`.
- The validation error will be raised when the invalid value as an attribute value will be provided.
- There will be options to decide what should happen when not all required attributes will be provided during `OrderCreateFromCheckout` mutation. Available options will be:
  - `IGNORE_INVALID`  - will ignore invalid attribute values - empty values will be set, the valid ones will be saved, and an order will be created
  - `DISCARD_ATTRIBUTES`  - when any error for attributes will appeared, all attributes values will be discarded, and order with no attribute values will be created
  - `RAISE_ERROR`  - will raise an error when not all required attribute values will be provided, the order will be not created

   Default option: `RAISE_ERROR `  

## Database changes
Add a `ManyToMany` relation between `SiteSettings`  and `Attribute` model.
```python
class SiteSettings:
    ...
    order_attributes = ManyToManyField(Attribute)
```

Add models for keeping the order attribute values. Here is the proposed solution:

## API changes
- Allow setting order attributes. Update input for `OrderSettingsUpdate`  mutation.
```graphql
input OrderSettingsUpdateInput {
  ...
  addAttributes: [ID!]
  removeAttributes: [ID!]
}
```
- Update `OrderSettings` type to allow fetching assigned attributes
```graphql
type OrderSettings {
  ...
  attributes: [Attribute!]
}
```
- Update the `OrderCreateFromCheckout` mutation to allow providing the attribute values. Add an option to choose the behavior when not all required attributes will be provided.
	Default option: `RAISE_ERROR`
```graphql
enum invalidAttributesErrorFallabackEnum{
  DISCARD_ATTRIBUTES
  INGNORE_INVALID
  RAISE_ERROR
}

type Mutation{
  ...
  orderCreateFromCheckout(
     ...
     attributes: [AttributeValueInput!]
     invalidAttributesErrorFallaback: invalidAttributesErrorFallabackEnum!
  ): OrderCreateFromCheckout
}
```

# Impact

* [ ] New migrations
* [ ] New/Updated API fields or mutations
* [ ] Deprecated API fields or mutations
* [ ] Removed API types, fields, or mutations
* [ ] Documentation needs to be updated

# Pull Request Checklist

* [ ] Privileged queries and mutations are guarded by proper permission checks
* [ ] Database queries are optimized and the number of queries is constant
* [ ] Database migration files are up to date
* [ ] The changes are tested
* [ ] GraphQL schema and type definitions are up to date
* [ ] Changes are mentioned in the changelog

### CODE REVIEW

**Comment by patrys** [comment]
Task linked: [SALEOR-7747 Order attributes](https://app.clickup.com/t/2549495/SALEOR-7747)

**Comment by korycins** [comment]
> The attributes could be assigned in the following mutations:
OrderCreateFromCheckout,
OrderUpdate,
DraftOrderUpdate,
DraftOrderCreate.

[Question] To keep a consistency with the rest attribute's types like Page/Product, shouldn't we have mutations like `OrderAttributeAssign`, `OrderAttributeUnasign`? I see such apporach in both types (Page, Product) so I assume that this is something common

**Comment by korycins** [comment]
> There will be options to decide what should happen when not all required attributes will be provided during OrderCreateFromCheckout mutation. 

What about `CheckoutComplete` mutation? What is expected behaviour for it when attributes are declared for the orders

**Comment by IKarbowiak** [comment]
@korycins 
>To keep a consistency with the rest attribute's types like Page/Product, shouldn't we have mutations like OrderAttributeAssign, OrderAttributeUnasign? I see such apporach in both types (Page, Product) so I assume that this is something common

Maybe we should 🤔. But I'm not sure if it's required as you can update attributes using `OrderSettingsUpdateInput`.

> What about CheckoutComplete mutation? What is expected behaviour for it when attributes are declared for the orders

Orders created with this mutation will always have empty attribute values.

**Pull request closed without merging**
