### PR TITLE
Try to solve those issues  #8069  #9012  #7385  #7135  #7279

### PR DESCRIPTION
**Pull request by slamer59**
Many issues have been open:
 #8069
 #9012
 #7385
 #7135
 #7279

I want to merge this change because it doesnot seems to break testing ? 

# Impact
* [ ] Tests ?

# Pull Request Checklist

* [ ] Privileged queries and mutations are guarded by proper permission checks
* [ ] Database queries are optimized and the number of queries is constant
* [ ] Database migration files are up to date
* [ ] The changes are tested
* [ ] GraphQL schema and type definitions are up to date
* [ ] Changes are mentioned in the changelog

### CODE REVIEW

**Comment by slamer59** [comment]
Automatic Naming of VCR seems to be the problem.
Should be updated. 
https://vcrpy.readthedocs.io/en/latest/configuration.html

**Comment by korycins** [comment]
Hey @slamer59  
Thanks for raising this. It looks like VCR doesn't recognize changed path (failed tests).
IMHO The proper way to do that is to modify failing tests. Instead of using @pytest.mark.vcr, we should use a standrad vcr wrapper with context manager. Something like:
```
def test_get_oembed_data(url, expected_media_type):
    with vcr.use_cassette('<properly converted url as a cassete name>') as cass:
        oembed_data, media_type = get_oembed_data(url, "media_url")
```
(You could user `url` here to build a proper cassete filename

**Comment by slamer59** [comment]
Hello,
Yes I didnt know VCR. If it is onoy those file I can manually fixe it like you said. 

I will fixe it this week.

**Comment by slamer59** [comment]
It is a bit tricky to convert from URL to URI. This proposal is to see if it is working.

**Comment by maarcingebala** [comment]
Thank you for your contribution! We decided on a different approach with using pytest-recording, see PR #9236.

**Pull request closed without merging**
