### PR TITLE
Backorder Feature

### PR DESCRIPTION
**Pull request by rrustvold**
From this issue https://github.com/mirumee/saleor/issues/4190 these changes create a minimal feature for supporting backorders/preorders. The feature is configurable per channel via a plugin (although there isn't any configuration options besides active or inactive). It doesn't support limiting backorders like the original issue suggests. As part of this three new OrderEvents are created to help keep a paper trail of backorders. I can create unit tests for this if the maintainer(s) are interested in the feature as I've conceived of it here. 

Concept: The idea is that tracking backorders is similar to tracking warehouse allocations. If there is not enough stock of a variant to create a full allocation, then when the InsufficientStockError is risen, an entry in the Backorder table is created if the plugin is active. As new stock is added to inventory, backorders are converted into allocations in a first-in-first-out order. 

https://github.com/mirumee/saleor/issues/4190 

Thank you!

# Impact

* [x] New migrations
* [x] New/Updated API fields or mutations
* [ ] Deprecated API fields or mutations
* [ ] Removed API types, fields, or mutations
* [x] Documentation needs to be updated

# Pull Request Checklist

* [x] Privileged queries and mutations are guarded by proper permission checks
* [x] Database queries are optimized and the number of queries is constant
* [x] Database migration files are up to date
* [ ] The changes are tested
* [x] GraphQL schema and type definitions are up to date
* [ ] Changes are mentioned in the changelog

### CODE REVIEW

**Comment by patrys** [comment]
Hello, the core team is currently jam-packed with the 3.0 release and Saleor Cloud work, so it may take some time to review pull requests submitted by the community.

We are currently working on a similar feature to support preorders in Saleor 3.1. It would be best to park this until preorders are merged to see if preorders and backorders could share the same models or logic.

**Comment by fowczarek** [comment]
If you are interested in the current state of preorders, you could check it out [here](https://github.com/mirumee/saleor/tree/feature/SALEOR-2998-preorders). It's still a work in progress.

**Comment by rrustvold** [comment]
> If you are interested in the current state of preorders, you could check it out [here](https://github.com/mirumee/saleor/tree/feature/SALEOR-2998-preorders). It's still a work in progress.

Thank you! I'll follow that branch. It looks like the approach there for pre-orders is quite similar to what I have here for back orders.

**Comment by maarcingebala** [comment]
We discussed the status of this PR recently and have decided not to merge it to the core for a few reasons. We're trying to limit the features added to core to a minimum and focus on extensibility via webhooks and building new features as Saleor Apps. This PR relies on plugins, which we will be migrating to apps in the future and don't want to invest too much effort into them currently. We appreciate the amount of work put into this PR and willing to contribute to the platform 🙌 .

**Comment by simon-online** [comment]
Would it be possible to get backorders added to the roadmap? I have a client who requires support for backorders so in the meantime I'll need to find a workaround.

> Hello, the core team is currently jam-packed with the 3.0 release and Saleor Cloud work, so it may take some time to review pull requests submitted by the community.
> 
> We are currently working on a similar feature to support preorders in Saleor 3.1. It would be best to park this until preorders are merged to see if preorders and backorders could share the same models or logic.

**Pull request closed without merging**
