### PR TITLE
Simple (flat rate) taxes API

### PR DESCRIPTION
**Pull request by maarcingebala**
This feature branch contains implementation for the new tax API which will allow defining tax rates per country and tax classes and customize tax configuration per channel.

## Progress

- [x] Add tax models (#9839).
- [x] Add tax API queries (#9856). 
- [x] Add tax API mutations. (#9934).
- [x] Add API to query/update tax classes for products, product types and shipping methods. (#9999)
- [x] Drop Vatlayer. (#10335)
- [x] Add logic to use flat tax rates in internal calculations.
  - #10121
  - #10406
  - #10466
  - https://github.com/saleor/saleor/pull/10747
- [x] Add integration with apps.
  - https://github.com/saleor/saleor/pull/10585
- [x] Denormalize tax class relationship:
  - Product's or product type's tax class in the `OrderLine` model.
  - Shipping method's tax class in the `Order` model.
- [x] Deprecate old tax API.
- [ ] Add webhook events for tax objects.

## TODO before merging
- [x] Cleanup migrations (remove merge migrations; re-generate new ones with new numbers)
- [x] Cleanup tests (e.g. skipped tests)
- [x] Performance tests

## General assumptions

Introduce the following concepts:

- Tax configuration - a channel-specific configuration that can determine whether:
    - prices are entered with or without tax 
    - taxes should be charged in the given channel; can be overridden per country 
    - prices returned in the public product API (e.g. for rendering in the storefront) include the tax; can be overridden per country

    It's important that tax collection and tax calculation are not the same thing, we may still need to calculate taxes if prices are entered as gross amounts and tax collection is disabled just to know what the amount is. For example: a channel for B2B sales could disable tax collection for all countries.

    Tax configuration objects will be created for each existing channel with data migration and for any new channel in the `channelCreate` mutation.

- Tax class - a named object that provides tax rates for specific countries. Product types are assigned to tax classes. Optionally products can override the tax class defined by the product type. Shipping methods can be also assigned to tax classes to define tax rates for shipping. Examples of tax groups: "Default", "Perfume", "Books", "Beer".

When presenting a product price, use the assigned group and user's country to determine if that group has a special rate assigned to it or if the default tax rate of the country is to be used. When calculating the shipping, check if the country has a special tax rate assigned for shipping or if the default tax rate of the country is to be used.

### App interaction

- Use country tax configuration existence to determine whether to invoke the tax webhook.
- If country configuration exists (even if tax collection is disabled for the current channel), use the above logic to calculate taxes and don't call the webhook.
-  If country configuration doesn't exist, call the synchronous tax webhook
- Create tax classes for each tax code assigned to products, copy the tax code to its metadata, and assign those products to the tax class.
- Update the Avatax plugin to use tax class metadata to determine the tax code instead of product metadata.

### Drop Vatlayer

Vatlayer plugin will be removed after merging these changes as most of its logic will be done be Saleor.

## Model changes

```mermaid
 classDiagram

  TaxClass "1" -- "*" TaxClassCountryRate
  TaxClass "1" -- "*" ProductType
  TaxClass "1" -- "*" Product
  TaxClass "1" -- "*" ShippingMethod
  TaxConfig "1" -- "*" TaxConfigPerCountry
  TaxConfig "1" -- "1" Channel

  class TaxClass {
    name: String
    is_default: Boolean
    product_types: [ProductType]
    products: [Product]
    shipping_method: [ShippingMethod]
    metadata: Metadata
}

class TaxClassCountryRate {
    country_code: String
    rate: Number
}

class TaxConfig {
    channel: Channel
    chargeTaxes: Boolean
    displayGrossPrices: Boolean
    pricesEnteredWithTax: Boolean
    metadata: Metadata
}

class TaxConfigPerCountry {
    countryCode: String
    chargeTaxes: Boolean
    displayGrossPrices: Boolean
}
```

### Deprecated API

- Deprecate inputs: `ProductCreateInput.chargeTaxes`, `ProductInput.chargeTaxes`
- Deprecate current tax settings in the Shop type: `includeTaxesInPrices`, `chargeTaxesOnShipping`, `displayGrossPrices` - will be replaced with new `TaxChannelConfiguration` type.
- Deprecate `CountryDisplay.vat` 

### Types

```graphql
enum TaxCalculationStrategy {
  FLAT_RATES
  TAX_APP
}

type TaxChannelConfiguration {
  id: ID!
  channel: Channel!
  chargeTaxes: Boolean!
  taxCalculationStrategy: TaxCalculationStrategy
  displayGrossPrices: Boolean!
  pricesEnteredWithTax: Boolean!
  countries: [TaxConfigurationPerCountry!]!
  privateMetadata: [MetadataItem!]!
  privateMetafield(key: String!): String
  privateMetafields(keys: [String!]): Metadata
  metadata: [MetadataItem!]!
  metafield(key: String!): String
  metafields(keys: [String!]): Metadata
}

type TaxConfigurationPerCountry {
  countryCode: String!
  chargeTaxes: Boolean!
  taxCalculationStrategy: TaxCalculationStrategy
  displayGrossPrices: Boolean!
}

type TaxClass {
  id: ID!
  name: String!
  isDefault: Boolean!
  countries: [TaxClassCountryRate!]
  privateMetadata: [MetadataItem!]!
  privateMetafield(key: String!): String
  privateMetafields(keys: [String!]): Metadata
  metadata: [MetadataItem!]!
  metafield(key: String!): String
  metafields(keys: [String!]): Metadata
}

type TaxClassCountryRate {
  countryCode: String!
  taxClass: TaxClass!
  rate: Float!
}

type TaxCountryConfiguration {
  countryCode: String!
  taxClassCountryRates: [TaxClassCountryRate!]!
}

# change existing types:

type ProductPricingInfo {
  displayGrossPrices: Boolean!
}

type Order {
  displayGrossPrices: Boolean!
}

type Checkout {
  displayGrossPrices: Boolean!
}
```

### Queries

All queries require `MANAGE_TAXES` permission. (For simplicity skipped definitions of connections and filtering and sorting inputs).

```graphql
type Query {

  taxConfigurations(
    filter: TaxConfigurationFilterInput,
    sortBy: TaxConfigurationSortingInput,
    before: String,
    after: String,
    first: Int,
    last: Int
  ): TaxConfigurationCountableConnection

  taxConfiguration(id: ID!): TaxConfiguration

  taxClasses(
    filter: TaxClassFilterInput,
    sortBy: TaxClassSortingInput,
    before: String,
    after: String,
    first: Int,
    last: Int
  ): TaxClassCountableConnection
 
  taxClass(id: ID!): TaxClass

  taxCountryConfigurations: [TaxCountryConfiguration!]!

  taxCountryConfiguration(countryCode: CountryCode!): TaxCountryConfiguration!
}
```

### Mutations

All mutations require `MANAGE_TAXES` permission.

```graphql
type Mutation {
  taxConfigurationUpdate(id: ID!, input: TaxConfigurationUpdateInput!): TaxConfigurationUpdate!
  taxClassCreate(input: TaxClassCreateInput!): TaxClassCreate!
  taxClassUpdate(id: ID!, input: TaxClassUpdateInput!): TaxClassUpdate!
  taxClassDelete(id: ID!): TaxClassDelete!
  taxCountryConfigurationUpdate(countryCode: CountryCode!, input: TaxCountryConfigurationUpdateInput!): TaxCountryConfigurationUpdate!
  taxCountryConfigurationDelete(countryCode: CountryCode!): TaxCountryConfigurationDelete!
}
```

#### taxConfigurationUpdate

```graphql
type TaxConfigurationUpdate {
  errors: [TaxConfigurationUpdateError!]!
  taxConfiguration: TaxConfiguration
}

type TaxConfigurationUpdateError {
  field: String
  message: String
  code: TaxConfigurationUpdateErrorCode!
}

enum TaxConfigurationUpdateErrorCode {
  GRAPHQL_ERROR
  DUPLICATED_INPUT_ITEM
}

input TaxConfigurationPerCountryInput {
  countryCode: CountryCode!
  chargeTaxes: Boolean!
  taxCalculationStrategy: TaxCalculationStrategy
  displayGrossPrices: Boolean!
}

input TaxConfigurationUpdateInput {
  chargeTaxes: Boolean!
  taxCalculationStrategy: TaxCalculationStrategy
  displayGrossPrices: Boolean
  pricesEnteredWithTax: Boolean
  updateCountriesConfiguration: [TaxConfigurationPerCountryInput!]
  removeCountriesConfiguration: [CountryCode!]  # using countryCode as identifier
}
```

#### taxClassCreate

```graphql
input CountryRateInput {
  countryCode: CountryCode!
  rate: Float!
}

input TaxClassCreateInput {
  name: String!
  updateCountryRates: [CountryRateInput!]
}

type TaxClassCreate {
  errors: [TaxClassCreateError!]!
  taxClass: TaxClass
}

type TaxClassCreateError {
  field: String
  message: String
  code: TaxClassCreateErrorCode!
}

enum TaxClassCreateErrorCode {
  GRAPHQL_ERROR
  DUPLICATED_INPUT_ITEM
}
```

#### taxClassUpdate

```graphql
input TaxClassUpdateInput {
  name: String
  updateCountryRates: [CountryRateInput!]
  removeCountryRates: [CountryCode!]  # using countryCode as identifier
}

type TaxClassUpdate {
  errors: [TaxClassUpdateError!]!
  taxClass: TaxClass
}

type TaxClassUpdateError {
  field: String
  message: String
  code: TaxClassUpdateErrorCode!
}

enum TaxClassUpdateErrorCode {
  GRAPHQL_ERROR
}
```

#### taxClassDelete

```graphql
type TaxClassDelete {
  errors: [TaxClassDeleteError!]!
  taxClass: TaxClass
}

type TaxClassDeleteError {
  field: String
  message: String
  code: TaxClassDeleteErrorCode!
}

enum TaxClassDeleteErrorCode {
  CANNOT_REMOVE_DEFAULT_CLASS
  GRAPHQL_ERROR
}
```

#### taxCountryConfigurationUpdate

```graphql
input TaxClassRateInput {
  taxClassId: ID!
  rate: Float  # accepts null; when null is provided remove this rate for this class/country
}

input TaxCountryConfigurationUpdateInput {
  countryCode: CountryCode!
  updateTaxClassRates: [TaxClassRateInput!]
}

type TaxCountryConfigurationUpdate {
  taxCountryConfiguration: TaxCountryConfiguration
  errors: [TaxCountryUpdateConfigurationError!]!
}

type TaxCountryUpdateConfigurationError {
  field: String
  message: String
  code: TaxCountryConfigurationUpdateErrorCode!
}

enum TaxCountryConfigurationUpdateErrorCode {
  GRAPHQL_ERROR
}
```

#### taxCountryConfigurationDelete

```graphql
type TaxCountryConfigurationDelete {
  taxCountryConfiguration: TaxCountryConfiguration
  errors: [TaxCountryDeleteConfigurationError!]!
}

type TaxCountryDeleteConfigurationError {
  field: String
  message: String
  code: TaxCountryDeleteConfigurationErrorCode!
}

enum TaxCountryDeleteConfigurationErrorCode{
  GRAPHQL_ERROR
}
```

## Tax exemption API (will be done as separate PR)

API to mark a particular checkout/order as tax-exempt (turn of tax collection). Privileged only for apps with proper permissions.

# Impact

* [x] New migrations
* [x] New/Updated API fields or mutations
* [x] Deprecated API fields or mutations
* [ ] Removed API types, fields, or mutations
* [x] Documentation needs to be updated

# Pull Request Checklist

* [ ] Privileged queries and mutations are guarded by proper permission checks
* [ ] Database queries are optimized and the number of queries is constant
* [ ] Database migration files are up to date
* [ ] The changes are tested
* [ ] GraphQL schema and type definitions are up to date
* [ ] Changes are mentioned in the changelog

### CODE REVIEW

**Comment by Qasem-h** [comment]
@maarcingebala Simple taxes API feature will be add in the 3.6 version?

**Comment by maarcingebala** [comment]
Hey @Qasem-h, we're aiming to release it in Saleor 3.7 (you can check it by the currently assigned milestone).

**Comment by carlosa54** [comment]
Nice 🚀 

After this is merged I think that there won't be no need for the plugin I created here https://github.com/carlosa54/saleor-flat-tax-plugin

**Comment by maarcingebala** [comment]
@carlosa54 Nice work with the plugin! 🚀

**Review by karolm-saleor — CHANGES_REQUESTED** [review]
Please add business background and acceptance criteria to the task description

**Review by jakubkuc — APPROVED** [review]

**Review by IKarbowiak — APPROVED** [review]

**Pull request merged**
