### PR TITLE
Don't run Saleor or Celery by default inside a devcontainer

### PR DESCRIPTION
**Pull request by patrys**
This requires people to run `uvicorn saleor.asgi:application` manually in a terminal but it makes it easier to debug and/or restart. It's also closer to the flow of working without devcontainers.

Update: Celery is now also not started manually. In exchange VSCode is preconfigured to launch either with a single click (and debugger support).

# Impact

- [ ] New migrations
- [ ] New/Updated API fields or mutations
- [ ] Deprecated API fields or mutations
- [ ] Removed API types, fields, or mutations

# Docs

- [ ] Link to documentation:

# Pull Request Checklist

- [ ] Privileged queries and mutations are either absent or guarded by proper permission checks
- [ ] Database queries are optimized and the number of queries is constant
- [ ] Database migrations are either absent or optimized for zero downtime
- [ ] The changes are covered by test cases

### CODE REVIEW

**Review by korycins — APPROVED** [review]
@patrys  Don't we need to mention somewhere about this? Looks like, we are adding an additional step that might not be clear to everyone.

**Review by fowczarek — APPROVED** [review]

**Comment by patrys** [comment]
@korycins AFAIK, we don't have any docs yet for dev containers?

**Comment by korycins** [comment]
So maybe at least a task on saleor-docs, to add this part when we will have more details about dev containers. Or a blank chapter with a note about this. 
It looks like a possible annoying thing, that we don't explain anywhere (it worked previously, now we need to run an additional command).

**Comment by kadewu** [comment]
What if we add page to docs and explain that you can change command for better debugging experience instead of doing this change permanently in code? 

I do personally believe, that leaving the command has more benefits, as e.g. when trying to run someone code I tend to check docker-compose for that information.

**Comment by patrys** [comment]
I've added VSCode launch configuration, so it now takes a single click to get Saleor running, including debugger and breakpoint support.

**Pull request merged**
