### PR TITLE
fix clean seo data error when null is passed

### LINKED ISSUE #13512: Bug: argument of type 'NoneType' is not iterable
### What are you trying to achieve?

Create a category with `null` passed as `seo` value in the input.

### Steps to reproduce the problem

1. Run the following mutation:
```graphql
mutation CreateCategory($input: CategoryInput!, $parentId: ID) {
  categoryCreate(input: $input, parent: $parentId) {
    errors {
      code
    }
    category {
      id
    }
  }
}
```

Variables:

```json
{
  "input": {
    "backgroundImage": null,
    "backgroundImageAlt": "Root",
    "description": "{\"blocks\":[{\"type\":\"paragraph\", \"data\":\"\"}]}",
    "metadata": null,
    "name": "Root",
    "privateMetadata": null,
    "seo": null,
    "slug": "root"
  },
  "parentId": null
}
```

2. It crashes with the following error:

```json
{
  "errors": [
    {
      "message": "argument of type 'NoneType' is not iterable",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "categoryCreate"
      ],
    }
  ],
  "data": {
    "categoryCreate": null
  },
}
```

API crashes in the `clean_seo_fields` function when `null` is passed as `seo` value. 

### What did you expect to happen?

In this case, the API shouldn't crash; it should ignore the SEO value and create the category without it.

### Logs

_No response_

### Environment

Saleor version: 3.14

### PR DESCRIPTION
**Pull request by ssuraliya**
I want to merge this change because fix clean seo data error when null is passed as seo value.

Fixes #13512 .

clean_seo_fields method in graphql>core>validators threw an error 'seo' parameter was passed as 'None'. Fixed it by applying a 
null check.

# Impact

* [ ] New migrations
* [ ] New/Updated API fields or mutations
* [ ] Deprecated API fields or mutations
* [ ] Removed API types, fields, or mutations
* [ ] Documentation needs to be updated

# Pull Request Checklist

* [ ] Privileged queries and mutations are either absent or guarded by proper permission checks
* [ ] Database queries are optimized and the number of queries is constant
* [ ] Database migrations are either absent or optimized for zero downtime
* [x] The changes are covered by test cases

### CODE REVIEW

**Comment by maarcingebala** [comment]
@ssuraliya Thanks for contributing to Saleor. We also need a unit test for each bugfix to check that the fixed behavior is working properly. The unit test should fail without the changes and pass after they're added to the codebase.

**Comment by ssuraliya** [comment]
@maarcingebala I have added the expected unit test.

**Review by maarcingebala — APPROVED** [review]
@ssuraliya Looks good now, you can also add an entry to the CHANGELOG.md file, and then your changes will be mentioned in the next release notes. You can add it in 3.15 > Other Changes section.

**Review by 8r2y5 — APPROVED** [review]

**Comment by ssuraliya** [comment]
I have resolved the merge conflict, would like to request further approval @maarcingebala

**Review by IKarbowiak — APPROVED** [review]

**Comment by maarcingebala** [comment]
@ssuraliya Thanks, the PR needs to be tested by our QA team before we can merge; we'll let you know if there is anything missing, if not I'll merge it as soon as it's tested.

**Review by jakubkuc — APPROVED** [review]

**Review by szczecha — APPROVED** [review]

**Comment by maarcingebala** [comment]
Merged, thank you for contributing to Saleor @ssuraliya 🎉

**Pull request merged**
