### PR TITLE
Use replicas on order queries

### PR DESCRIPTION
**Pull request by tomaszszymanski129**
I want to merge this change because order queries used to be executed on the writer which shouldn't be the case.

# Impact

* [ ] New migrations
* [ ] New/Updated API fields or mutations
* [ ] Deprecated API fields or mutations
* [ ] Removed API types, fields, or mutations
* [ ] Documentation needs to be updated

# Pull Request Checklist

* [ ] Privileged queries and mutations are guarded by proper permission checks
* [ ] Database queries are optimized and the number of queries is constant
* [ ] Database migration files are up to date
* [ ] The changes are tested
* [ ] GraphQL schema and type definitions are up to date
* [ ] Changes are mentioned in the changelog

### CODE REVIEW

**Comment by patrys** [comment]
Task linked: [CLOUD-2743 use read replica when querying orders](https://app.clickup.com/t/2549495/CLOUD-2743)

**Review by IKarbowiak — APPROVED** [review]

**Review by fowczarek — APPROVED** [review]
Do you consider passing to resolvers only connection_name instead of the whole context?

**Comment by tomaszszymanski129** [comment]
> Do you consider passing to resolvers only connection_name instead of the whole context?

in some other resolvers we use that exact pattern, however that's a good point, we don't need an entire object.

**Comment by tomaszszymanski129** [comment]
@fowczarek @IKarbowiak changed the passing context pattern to pass only connection names. Refactored also product resolvers where we had the same thing.

**Review by 8r2y5 — APPROVED** [review]

**Pull request merged**
