### PR TITLE
New playground

### PR DESCRIPTION
**Pull request by mmiszy**
I want to merge this change because the new GraphQL playground is more extensible and powerful.

Demo: https://saleor-graphql-playground.vercel.app/

https://app.clickup.com/t/2549495/SALEOR-7662

Comparison:

| feature             | old    | new    |
| ------------------- | ------ | ------ |
| tabs                | ✅ yes | ✅ yes |
| query variables     | ✅ yes | ✅ yes |
| http headers        | ✅ yes | ✅ yes |
| docs                | ✅ yes | ✅ yes |
| prettify            | ✅ yes | ✅ yes |
| history             | ✅ yes | ✅ yes |
| search in schema    | 😄 kind of  | ✅ yes |
| sharing via URL     | ❌ no  | ✅ yes |
| editor settings     | ✅ yes | ✅ yes  |
| dark mode     | ✅ yes | ✅ yes  |
| easier to customize | ❌ no  | ✅ yes |

# Impact

* [ ] New migrations
* [ ] New/Updated API fields or mutations
* [ ] Deprecated API fields or mutations
* [ ] Removed API types, fields, or mutations
* [ ] Documentation needs to be updated

# Pull Request Checklist

* [x] Privileged queries and mutations are guarded by proper permission checks
* [x] Database queries are optimized and the number of queries is constant
* [x] Database migration files are up to date
* [x] The changes are tested
* [x] GraphQL schema and type definitions are up to date
* [ ] Changes are mentioned in the changelog

### CODE REVIEW

**Comment by patrys** [comment]
Can we get a feature parity comparison?

**Comment by mmiszy** [comment]
Added to the description @patrys: https://github.com/saleor/saleor/pull/10338#issue-1333188425

**Comment by patrys** [comment]
@mmiszy Old Playground has search in Schema, you can click any panel and press Cmd+F. New tool seems to lack support for dark mode.

**Comment by mmiszy** [comment]
Some comments left on Slack by @fowczarek. I'll follow up on them.

**Comment by maarcingebala** [comment]
@mmiszy Should I keep this PR or are we going to open a new one to upgrade to GraphiQL v2?

**Comment by mmiszy** [comment]
@maarcingebala we already heave a new one in testing; I'll update this PR when it's tested: https://saleor-graphql-playground-3z2a012bw-saleorcommerce.vercel.app

**Comment by mmiszy** [comment]
Updated

**Review by maarcingebala — APPROVED** [review]

**Review by IKarbowiak — APPROVED** [review]

**Review by jakubkuc — APPROVED** [review]

**Pull request merged**
